# thistuple = ("apple", "banana", "cherry", "apple", "cherry")
# print(thistuple)
# print(len(thistuple))
# thistuple2= ('apple',)
# print*(type(thistuple2))
# thistuple = ("apple",)
# print(type(thistuple))
# thistuple = ('apple',)
# print(type(thistuple))
# thistuple = ('apple')
# print(type(thistuple))
# tuple1 = ('apple', 'banana', 'cherry')
# tuple2= (1,5,7,9,3)
# tuple3= (True,False,True)
# tuple4 =('abc', 44, True, -56, 'male')
# print(type(tuple4))
# thistuple = tuple(('apple', 'banana', 'cherry'))
# print(thistuple)
# thistuple = ("apple", "banana", "cherry")
# print(thistuple[1])
# print(thistuple[0])
# print(thistuple[-1])
# thistuple = ("apple", "banana", "cherry", "orange", "kiwi", "melon", "mango")
# print(thistuple[2:5])
# print(thistuple[:4])
# print(thistuple[2:])
# print(thistuple[-4:-1])
# if 'banana' in thistuple:
#     print('yes, apple is in the fruits tuple')
# x = ("apple", "banana", "cherry")
# y = list(x)
# y[1] = "kiwi"
# x = tuple(y)
# print(x)
# x = ('apple', 'banana', 'cherry')
# y = list(x)
# y[1]= 'kiwi'
# x = tuple(y)
# print(x)
# thistuple = ('apple', 'banana', 'cherry')
# y = list(thistuple)
# y.append('orange')
# thistuple = tuple(y)
# print(thistuple)
# thistuple = ("apple", "banana", "cherry")
# y = ('orange',)
# thistuple += y
# print(thistuple)
# thistuple = ('apple', 'banana', 'cherry')
# y = ('orange',)
# thistuple += y
# print(thistuple)
# thistuple = ('apple', 'banana', 'cherry')
# y = list(thistuple)
# y.remove('apple')
# thistuple = tuple(y)
# print(thistuple)
# thistuple = ('apple', 'cherry', 'orange')
# del thistuple
# print(thistuple)
# fruits = ('apple', 'banana', 'cherry')
# (green, yellow, red) = fruits
# print(green)
# print(yellow)
# print(red)
# fruits = ("apple", "banana", "cherry", "strawberry", "raspberry")
# (green, yellow, *red) = fruits
# print(red)
# (green, yellow, red) = fruits
# print(yellow)
# print(red)
# fruits = ("apple", "banana", "cherry", "strawberry", "raspberry")
# (*red, yellow)=fruits
# print(red)
# fruits = ("apple", "mango", "papaya", "pineapple", "cherry")
# (green, *tropic, red) = fruits
# print(green)
# print(tropic)
# print(red)
# thistuple = ("apple", "banana", "cherry")
# for x in thistuple:
#     print(x)
# thistuple = ('green', 'yellow', 'red')
# for i in range(len(thistuple)):
#     print(thistuple[i])
# thistuple =('apple', 'banana' , 'cherry')
# for i in range(len(thistuple)):
#     print(thistuple[i])
# thistuple = ("apple", "banana", "cherry")
# i = 0
# while i < len(thistuple):
#     print(thistuple[i])
#     i = i + 1
# tuple1 = ("a", "b" , "c")
# tuple2 = (1, 2, 3)
# tuple3 = tuple1 + tuple2
# print(tuple3)
# fruits = ("apple", "banana", "cherry")
# mytuple = fruits * 3
# print(mytuple)
